---

- name: Interfaces konfigurieren
  hosts: router

  vars_files:
  - vars/interface_params.yaml
  - vars/basic_vars.yaml

  tasks:
  - name: policy map anlegen
    ios_config:
      lines:
      - police rate 10000000 bps
      parents:
      - policy-map 10Mb
      - class class-default
      
  - name: configurable backup path 
    ios_config:
      src: "{{ pfad_j2 }}/{{ j2_template }}"
      backup: yes
      backup_options:
        dir_path: "{{ pfad_cfg }}/{{ ansible_net_hostname }}"
        filename: backup_{{ ansible_net_hostname }}.cfg

...
