---
  - name: liste mit interfaces (aus vars) bei allen routern
    debug:
      msg: "{{ item[1].ip }}"
      # wird angezeigt nur ab -v
      # verbosity: 1
    loop: "{{ configurations.values() | list | subelements('ip_interfaces') }}"
    loop_control:
      label: "{{ item[1].ip }}"
    run_once: true

  - name: konnektivitaet testen
    net_ping:
      dest: "{{ item[1].ip }}"
      count: 10
    loop: "{{ configurations.values() | list | subelements('ip_interfaces') }}"
    loop_control:
      label: "{{ item[1].ip }}"
    register: ping_status

  - name: info ueber pings
    debug:
      msg: "Packet loss ist: {{ item.packet_loss }}"
    loop: "{{ ping_status.results }}"
    loop_control:
      label: "{{ item.commands }}"
...
